### ISSUE TITLE
Won't load on Google Site

### ISSUE THREAD

**Issue by steddy** [kyco/jquery.kyco.googleplusfeed2#10]
Hi there.  I've successfully tested the widget on my personal site (http://stedfast.net/design/gplus/gplus_test4.html), and I've now converted it into a Google Gadget in the same way I've done another gadget.  However, this widget is not loading when added to my Google Site as a gadget.  Typically, adding code as a gadget allows for the use of javascript, jquery, etc., which is ordinarily blocked on Google Sites.  Any thoughts about that?

**Comment by Corhero** [comment]
Hi

Only saw this now. Sorry for getting back to you so late. Hm that is a tricky one. I have no experience with Google Gadgets. What exactly happens? Does it keep loading forever or doesn't it even trigger the widget?

**Comment by steddy** [comment]
It looks like the widget content doesn't load.  I just get a blank background.  Right now, I'm just playing around with the site, so I don't mind leaving the blank gadget up there for you to take a look at: https://sites.google.com/a/eppingsd.org/philotic/.

Thank you!

**Comment by Corhero** [comment]
Think the issue is cross origin policy. I see `Blocked loading mixed active content "http://stedfast.net/design/gplus/jquery.kyco.googleplusfeed2.min.js"` in the dev console.
In this case you would have to load the content from `https://sites.google.com/a/eppingsd.org/philotic/`, i.e. move the `jquery.kyco.googleplusfeed2.min.js` and `jquery.kyco.googleplusfeed2.css` to that domain if you can.

**Comment by steddy** [comment]
Excellent catch.  I appreciate that you made the time to look into it and
offer the suggestion!  Thank you for sharing your fantastic gadget, too!

-Steddy

**Comment by Corhero** [comment]
Cool, no worries. Glad it's sorted.
